Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.define "kafka-vm1" do |vm1|
    vm1.vm.hostname = "kafka-vm1"
    vm1.vm.network "public_network", bridge: "Wi-Fi", ip: "192.168.1.101"
    vm1.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openjdk-21-jdk
      java -version
    SHELL
  end
  config.vm.define "kafka-vm2" do |vm2|
    vm2.vm.hostname = "kafka-vm2"
    vm2.vm.network "public_network", bridge: "Wi-Fi", ip: "192.168.1.102"
    vm2.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    vm2.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openjdk-21-jdk
      java -version
    SHELL
  end
end
