Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "public_network"
  config.vm.network "forwarded_port", guest: 22, host: 2223, id: "ssh"
  config.vm.synced_folder ".", "/vagrant_data", disabled: true

  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu_server"
    vb.memory = "1024"
    vb.cpus = 1
    vb.gui = false
  end
end
